/** Rule-based observations and CSV for Insights. Every observation lists the facts and assumptions behind it; nothing is generated by AI. */
import { DateTime } from 'luxon';
import { csvCell } from '../exports.js';
import type { Metrics, Ratio, Scope } from './orgdash.js';

export interface Observation {
  id: string; severity: 'attention' | 'info' | 'positive'; metric: string; group: string | null;
  title: string; facts: string[]; assumptions: string[];
}
interface WeekRow { start: string; end: string; complete: boolean; metrics: Metrics }
interface Input {
  scope: Scope; label: string; minGroup: number; weeks: WeekRow[]; totals: { current: Metrics; previous: Metrics };
  groups: { name: string; people: number; suppressed: boolean; weekly: Metrics[] | null }[];
  blockersByCause: { cause: string; active: number; raised: number; openAtEnd: number; medianAgeHours: number | null }[];
  workload: { horizonWorkingDays: number; totals: any; byGroup: any[] };
}

const pct = (v: number | null | undefined) => (v === null || v === undefined ? 'N/A' : `${Math.round(v * 100)}%`);
const hm = (m: number) => { const h = Math.floor(m / 60), r = Math.round(m % 60); return h ? `${h}h${r ? ` ${r}m` : ''}` : `${r}m`; };
const dur = (h: number) => { const d = Math.round((h / 24) * 10) / 10; return h < 24 ? `${Math.round(h * 10) / 10}h` : `${d} ${d === 1 ? 'day' : 'days'}`; };
const day = (s: string) => DateTime.fromISO(s, { zone: 'utc' }).toFormat('d LLL');
const span = (a: string, b: string) => `${day(a)} to ${day(b)}`;
const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;
const SEVERITY = { attention: 0, info: 1, positive: 2 } as const;

/** Compare the most recent complete weeks with the same number of weeks before them (2 vs 2 when possible, else 1 vs 1). */
function windows(weeks: WeekRow[]) {
  const idx = weeks.map((w, i) => (w.complete ? i : -1)).filter((i) => i >= 0);
  const n = idx.length >= 4 ? 2 : idx.length >= 2 ? 1 : 0;
  return n ? { n, recent: idx.slice(-n), prior: idx.slice(-2 * n, -n) } : null;
}
function pooled(series: Metrics[], idxs: number[], pick: (m: Metrics) => Ratio) {
  let num = 0, den = 0;
  for (const i of idxs) { const r = pick(series[i]); if (r.status !== 'not_applicable') { num += r.num; den += r.den; } }
  return { num, den, value: den > 0 ? num / den : null };
}

export function buildObservations(x: Input): Observation[] {
  const out: Observation[] = [];
  const cur = x.totals.current, prev = x.totals.previous;
  const w = windows(x.weeks);
  // Group observations only for groups of at least minGroup people: observations describe teams, never single individuals.
  const visibleGroups = x.groups.filter((g) => !g.suppressed && g.weekly && g.people >= x.minGroup);
  const subjects = [
    { name: x.label, group: null as string | null, people: cur.people, weekly: x.weeks.map((r) => r.metrics) },
    ...visibleGroups.filter((g) => g.people < cur.people).map((g) => ({ name: g.name, group: g.name, people: g.people, weekly: g.weekly! })),
  ];
  const where = (s: { group: string | null; name: string }) => (s.group ? `in ${s.name}` : x.label === 'the company' ? 'company-wide' : `in ${s.name}`);

  if (w) {
    const rs = { from: x.weeks[w.recent[0]].start, to: x.weeks[w.recent[w.recent.length - 1]].end };
    const ps = { from: x.weeks[w.prior[0]].start, to: x.weeks[w.prior[w.prior.length - 1]].end };
    const over = plural(w.n, 'week');
    for (const s of subjects) {
      const facts = (unit: (p: { num: number; den: number; value: number | null }) => string, a: any, b: any) =>
        [`${span(ps.from, ps.to)}: ${unit(a)}`, `${span(rs.from, rs.to)}: ${unit(b)}`, `${plural(s.people, 'person', 'people')} ${s.group ? `in ${s.name}` : 'in scope'}`];
      // Recap adoption
      let a = pooled(s.weekly, w.prior, (m) => m.recapAdoption), b = pooled(s.weekly, w.recent, (m) => m.recapAdoption);
      if (a.den >= 8 && b.den >= 8 && a.value !== null && b.value !== null && Math.abs(b.value - a.value) >= 0.15) {
        const fell = b.value < a.value;
        out.push({ id: `recap:${s.group ?? 'all'}`, severity: fell ? 'attention' : 'positive', metric: 'recapAdoption', group: s.group,
          title: `Recap adoption ${fell ? 'fell' : 'rose'} from ${pct(a.value)} to ${pct(b.value)} ${where(s)} over ${over}`,
          facts: facts((p) => `${p.num} of ${p.den} working person-days had a confirmed recap (${pct(p.value)})`, a, b),
          assumptions: ['Complete weeks only; the current week is excluded.', 'Holidays, approved leave and non-working days are not counted.'] });
      }
      // Planned-commitment completion
      a = pooled(s.weekly, w.prior, (m) => m.plannedCompletion); b = pooled(s.weekly, w.recent, (m) => m.plannedCompletion);
      if (a.den >= 10 && b.den >= 10 && a.value !== null && b.value !== null && Math.abs(b.value - a.value) >= 0.15) {
        const fell = b.value < a.value;
        out.push({ id: `commit:${s.group ?? 'all'}`, severity: fell ? 'attention' : 'positive', metric: 'plannedCompletion', group: s.group,
          title: `Planned-commitment completion ${fell ? 'fell' : 'rose'} from ${pct(a.value)} to ${pct(b.value)} ${where(s)} over ${over}`,
          facts: facts((p) => `${p.num} of ${p.den} intended outcomes accepted the same day (${pct(p.value)})`, a, b),
          assumptions: ['Intended outcomes are the up to three outcomes each person planned for the day.', 'Blocked or re-scoped work counts as not accepted; check blockers before drawing conclusions.'] });
      }
      // Logging coverage (record completeness, never productivity)
      a = pooled(s.weekly, w.prior, (m) => m.loggingCoverage); b = pooled(s.weekly, w.recent, (m) => m.loggingCoverage);
      if (a.den >= 1200 && b.den >= 1200 && a.value !== null && b.value !== null && Math.abs(b.value - a.value) >= 0.15) {
        out.push({ id: `coverage:${s.group ?? 'all'}`, severity: 'info', metric: 'loggingCoverage', group: s.group,
          title: `Logging coverage ${b.value < a.value ? 'fell' : 'rose'} from ${pct(a.value)} to ${pct(b.value)} ${where(s)} over ${over}`,
          facts: facts((p) => `${hm(p.num)} confirmed of ${hm(p.den)} available (${pct(p.value)}); ${hm(p.den - p.num)} unknown`, a, b),
          assumptions: ['Coverage shows how complete time records are. It is not productivity, and unknown time is not treated as idle.'] });
      }
      // Meeting load in the recent window
      b = pooled(s.weekly, w.recent, (m) => m.meetingShare); a = pooled(s.weekly, w.prior, (m) => m.meetingShare);
      if (b.den >= 1200 && b.value !== null && b.value >= 0.35) {
        out.push({ id: `meetings:${s.group ?? 'all'}`, severity: 'info', metric: 'meetingShare', group: s.group,
          title: `Meetings took ${pct(b.value)} of available time ${where(s)} in the last ${over}`,
          facts: [`${hm(b.num)} of confirmed meetings in ${hm(b.den)} of available time (${span(rs.from, rs.to)})`,
            a.value !== null ? `Previous ${over}: ${pct(a.value)}` : 'No comparable previous window', `${plural(s.people, 'person', 'people')} ${s.group ? `in ${s.name}` : 'in scope'}`],
          assumptions: ['Only meetings recorded as confirmed time are counted.', 'Some roles (for example sales) expect a high meeting share.'] });
      }
    }
  }

  // Blockers: cause concentration and age (current period)
  const totalBlockers = x.blockersByCause.reduce((s, c) => s + c.active, 0);
  const top = x.blockersByCause[0];
  if (top && totalBlockers >= 4 && top.active >= 3 && top.active / totalBlockers >= 0.4) {
    out.push({ id: 'blockers:cause', severity: top.medianAgeHours !== null && top.medianAgeHours > 48 ? 'attention' : 'info', metric: 'blockers', group: null,
      title: `${top.cause[0].toUpperCase()}${top.cause.slice(1)} is the most common blocker cause (${top.active} of ${totalBlockers})`,
      facts: x.blockersByCause.map((c) => `${c.cause}: ${c.active} active, ${c.openAtEnd} still open, median age ${c.medianAgeHours === null ? 'N/A' : dur(c.medianAgeHours)}`),
      assumptions: ['Causes are chosen by the person who raised the blocker.'] });
  }
  if (cur.blockers.active >= 3 && cur.blockers.medianAgeHours !== null && cur.blockers.medianAgeHours > 48) {
    out.push({ id: 'blockers:age', severity: 'attention', metric: 'blockers', group: null,
      title: `Blockers stayed open for a median of ${dur(cur.blockers.medianAgeHours)}`,
      facts: [`${cur.blockers.active} blockers active in the period, ${cur.blockers.openAtEnd} still open at its end`,
        `Previous period median: ${prev.blockers.medianAgeHours === null ? 'N/A' : dur(prev.blockers.medianAgeHours)}`],
      assumptions: ['Age is measured until resolution, or until the end of the period for open blockers.'] });
  }
  // Deadlines
  const dc = cur.deadlineReliability, dp = prev.deadlineReliability;
  if (dc.den >= 5 && dp.den >= 5 && dc.value !== null && dp.value !== null && Math.abs(dc.value - dp.value) >= 0.15) {
    const fell = dc.value < dp.value;
    out.push({ id: 'deadlines:change', severity: fell ? 'attention' : 'positive', metric: 'deadlineReliability', group: null,
      title: `Deadline reliability ${fell ? 'fell' : 'rose'} from ${pct(dp.value)} to ${pct(dc.value)} versus the previous period`,
      facts: [`This period: ${dc.met} met, ${dc.late} late, ${dc.overdue} overdue`, `Previous period: ${dp.met} met, ${dp.late} late, ${dp.overdue} overdue`],
      assumptions: ['Only commitments with a due date are counted; items not yet due are excluded.'] });
  }
  if (dc.overdue >= 3) {
    out.push({ id: 'deadlines:overdue', severity: 'attention', metric: 'deadlineReliability', group: null,
      title: `${plural(dc.overdue, 'commitment')} due in this period ${dc.overdue === 1 ? 'is' : 'are'} still overdue`,
      facts: [`${dc.met} met and ${dc.late} late out of ${dc.den} resolved or overdue`], assumptions: ['Overdue means past the due date and not Done; cancelled work is excluded.'] });
  }
  // Rework
  if (cur.reworkRate.den >= 4 && cur.reworkRate.value !== null && cur.reworkRate.value >= 0.25) {
    out.push({ id: 'rework', severity: 'attention', metric: 'reworkRate', group: null,
      title: `${pct(cur.reworkRate.value)} of accepted outcomes needed rework before acceptance`,
      facts: [`${cur.reworkRate.num} of ${cur.reworkRate.den} accepted outcomes were reopened or had changes requested`, `Previous period: ${pct(prev.reworkRate.value)}`],
      assumptions: ['Rework can reflect unclear acceptance criteria as much as execution; check change-request notes.'] });
  }
  // WIP growth
  if (cur.wip.value !== null && prev.wip.value !== null && cur.wip.value - prev.wip.value >= 3 && cur.wip.value >= prev.wip.value * 1.3) {
    out.push({ id: 'wip', severity: 'info', metric: 'wip', group: null,
      title: `Work in progress rose from ${prev.wip.value} to ${cur.wip.value} tasks`,
      facts: [`${cur.wip.blocked} blocked and ${cur.wip.inReview} in review at the end of the period`, `Accepted outcomes: ${prev.acceptedOutcomes} in the previous period, ${cur.acceptedOutcomes} in this one`],
      assumptions: ['Status history is attributed to each task\'s current owner.'] });
  }
  // Workload (load, not performance)
  const wt = x.workload.totals;
  if (wt.overloaded >= 1) {
    out.push({ id: 'workload:over', severity: 'attention', metric: 'workload', group: null,
      title: `${plural(wt.overloaded, 'person', 'people')} ${wt.overloaded === 1 ? 'has' : 'have'} open estimated work above 125% of available time in the next ${x.workload.horizonWorkingDays} working days`,
      facts: [`Overall: ${hm(wt.estimatedMinutes)} estimated against ${hm(wt.availableMinutes)} available (${pct(wt.load.value)})`,
        ...x.workload.byGroup.filter((g: any) => !g.suppressed && g.overloaded).map((g: any) => `${g.name}: ${g.overloaded} above 125%`),
        x.scope.perPerson ? 'See the workload table (alphabetical) to rebalance.' : 'Department totals only; individual rows are not shown for this access level.'],
      assumptions: [`Only estimated open work counts; ${pct(wt.estimateCoverage)} of open tasks have estimates.`, 'This is load, not performance.'] });
  }
  if (wt.openTasks >= 5 && wt.estimateCoverage !== null && wt.estimateCoverage < 0.5) {
    out.push({ id: 'workload:estimates', severity: 'info', metric: 'workload', group: null,
      title: `Only ${pct(wt.estimateCoverage)} of open tasks have estimates, so workload figures are partial`,
      facts: [`${wt.estimatedTasks} of ${wt.openTasks} open tasks are estimated`], assumptions: ['Unestimated work is not assumed to be zero; it is simply not counted.'] });
  }
  // Estimates
  const ea = cur.estimateAccuracy;
  if (ea.n >= 5 && ea.value !== null && (ea.value >= 1.5 || ea.value <= 0.67)) {
    out.push({ id: 'estimates', severity: 'info', metric: 'estimateAccuracy', group: null,
      title: `Accepted work took ${ea.value.toFixed(1)}x its estimates`,
      facts: [`${hm(ea.actualMinutes)} confirmed against ${hm(ea.estimateMinutes)} estimated on ${ea.n} of ${ea.accepted} accepted outcomes`,
        `${pct(ea.withinBand)} of them landed within 25% of the estimate`],
      assumptions: ['Only outcomes with both an estimate and confirmed task time qualify.', 'Unrecorded time makes actuals a lower bound.'] });
  }
  // Cycle time
  const cc = cur.cycleTime, cp = prev.cycleTime;
  if (cc.n >= 5 && cp.n >= 5 && cc.medianHours !== null && cp.medianHours !== null && cc.medianHours >= cp.medianHours * 1.5 && cc.medianHours - cp.medianHours >= 24) {
    out.push({ id: 'cycle', severity: 'info', metric: 'cycleTime', group: null,
      title: `Median cycle time rose from ${dur(cp.medianHours)} to ${dur(cc.medianHours)}`,
      facts: [`${cc.n} accepted outcomes with a recorded start this period, ${cp.n} in the previous one`, `75th percentile now ${dur(cc.p75Hours!)}`],
      assumptions: ['Calendar time, including nights, weekends and waiting on blockers.'] });
  }
  return out.sort((p, q) => SEVERITY[p.severity] - SEVERITY[q.severity]);
}

// ---------------------------------------------------------------- CSV

const csv = (rows: unknown[][]) => rows.map((r) => r.map(csvCell).join(',')).join('\n') + '\n';
const rc = (r: { value: number | null; status: string }) => (r.status === 'not_applicable' ? 'N/A' : r.value === null ? '' : `${(r.value * 100).toFixed(1)}%`);
const n = (v: number | null | undefined) => (v === null || v === undefined ? '' : v);
const HEAD = ['working_person_days', 'recap_adoption', 'logging_coverage', 'unknown_min', 'planned_completion', 'accepted_outcomes', 'deadlines_met', 'deadlines_late',
  'deadlines_overdue', 'deadline_reliability', 'blockers_raised', 'blockers_active', 'blocker_median_age_h', 'cycle_median_h', 'cycle_p75_h', 'rework_rate', 'wip_end',
  'meeting_share', 'focus_share', 'estimate_ratio', 'estimate_qualifying'];
const metricCells = (m: Metrics) => [m.workingPersonDays, rc(m.recapAdoption), rc(m.loggingCoverage), m.loggingCoverage.unknownMinutes, rc(m.plannedCompletion), m.acceptedOutcomes,
  m.deadlineReliability.met, m.deadlineReliability.late, m.deadlineReliability.overdue, rc(m.deadlineReliability), m.blockers.raised, m.blockers.active, n(m.blockers.medianAgeHours),
  n(m.cycleTime.medianHours), n(m.cycleTime.p75Hours), rc(m.reworkRate), n(m.wip.value), rc(m.meetingShare), rc(m.focusShare), n(m.estimateAccuracy.value), m.estimateAccuracy.n];

export function insightsCsv(d: any) {
  const rows: unknown[][] = [
    ['Insights', d.scope.mode === 'team' ? 'Your teams' : 'Company-wide'], ['Period', `${d.period.start} to ${d.period.end}`],
    ['Previous period', `${d.period.previous.start} to ${d.period.previous.end}`], ['People in scope', d.scope.people], ['Generated', d.generatedAt], ['Definitions', d.version],
    ...d.scope.notes.map((x: string) => ['Note', x]),
    ['Note', 'N/A = not applicable (no scheduled working time); blank = no qualifying records.'],
  ];
  if (d.suppressed) return csv([...rows, ['Withheld', d.suppressed]]);
  if (!d.totals) return csv([...rows, ['Note', 'No people in this selection']]);
  rows.push([], ['Weekly'], ['week_start', 'week_end', 'partial', ...HEAD]);
  for (const w of d.weeks) rows.push([w.start, w.end, w.partial ? 'yes' : 'no', ...metricCells(w.metrics)]);
  rows.push([], ['Period totals'], ['period', 'start', 'end', ...HEAD],
    ['current', d.period.start, d.period.end, ...metricCells(d.totals.current)], ['previous', d.period.previous.start, d.period.previous.end, ...metricCells(d.totals.previous)]);
  rows.push([], ['Blockers by cause'], ['cause', 'active', 'raised', 'open_at_end', 'median_age_h'],
    ...d.blockersByCause.map((c: any) => [c.cause, c.active, c.raised, c.openAtEnd, n(c.medianAgeHours)]));
  rows.push([], ['Cycle time by category'], ['category', 'accepted', 'with_start', 'median_h', 'p75_h'],
    ...d.cycleTime.byCategory.map((c: any) => [c.category, c.accepted, c.n, n(c.medianHours), n(c.p75Hours)]));
  rows.push([], ['Cycle time distribution'], ['bucket', 'count'], ...d.cycleTime.distribution.map((b: any) => [b.label, b.count]));
  rows.push([], ['Departments (alphabetical)'], ['department', 'people', 'recap_adoption', 'logging_coverage', 'planned_completion', 'accepted_outcomes', 'deadline_reliability', 'meeting_share', 'rework_rate'],
    ...d.groups.map((g: any) => (g.suppressed ? [g.name, g.people, 'withheld (small group protection)'] : [g.name, g.people, rc(g.metrics.recapAdoption), rc(g.metrics.loggingCoverage),
      rc(g.metrics.plannedCompletion), g.metrics.acceptedOutcomes, rc(g.metrics.deadlineReliability), rc(g.metrics.meetingShare), rc(g.metrics.reworkRate)])));
  rows.push([], [`Workload: next ${d.workload.horizonWorkingDays} working days. ${d.workload.note}`]);
  if (d.workload.rows) {
    rows.push(['person', 'department', 'open_tasks', 'estimated_tasks', 'estimated_min', 'available_min', 'load', 'in_progress', 'blocked', 'in_review', 'overdue'],
      ...d.workload.rows.map((r: any) => [r.name, r.department ?? '', r.openTasks, r.estimatedTasks, r.estimatedMinutes, r.availableMinutes, rc(r.load), r.inProgress, r.blocked, r.inReview, r.overdue]));
  } else {
    rows.push(['department', 'people', 'open_tasks', 'estimated_min', 'available_min', 'load'],
      ...d.workload.byGroup.map((g: any) => (g.suppressed ? [g.name, g.people, 'withheld (small group protection)'] : [g.name, g.people, g.openTasks, g.estimatedMinutes, g.availableMinutes, rc(g.load)])));
  }
  rows.push([], ['Observations (rule-based)'], ['severity', 'observation', 'facts', 'assumptions'],
    ...d.observations.map((o: Observation) => [o.severity, o.title, o.facts.join(' | '), o.assumptions.join(' | ')]));
  return csv(rows);
}
